### // A petition starts
POST https://apirest-betymtz.herokuapp.com/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Lucy Gzm",
    "email": "lucygzmdl@gmail.com"
}  

###
POST https://apirest-betymtz.herokuapp.com/api/product HTTP/1.1
Content-Type: application/json

{
    "name": "Lenovo 2021",
    "price": 10000,
    "image": "imagen.jpg",
    "condition": "New",
    "Category": "Laptop",
    "Description": "4GB RAM - 2T DD - 16''FHD"
}

###
GET https://apirest-betymtz.herokuapp.com/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/61aaa967a832a02a9f8c0425 HTTP/1.1

###
PUT http://localhost:9000/api/users/61aaa967a832a02a9f8c0425 HTTP/1.1
Content-Type: application/json

{
    "name": "Vianney Baez",
    "email": "vbaez@gmail.com"
}  

###
DELETE http://localhost:9000/api/users/61aab1676657551c97733e4e HTTP/1.1
